name: Generate Friend Links Data

on:
  # Run when the workflow is triggered manually.
  workflow_dispatch:
  # Run when a modification is made to the issues.
  issues:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup rust-script
      run: cargo install rust-script
    - name: Run src/script.ers
      run: |
        chmod +x src/script.ers
        ./src/script.ers
    - name: Upload generated data
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: |
          ./output/linksData.js
          ./output/linksData.json
